### ISSUE TITLE
Srtool unnecessarily compiles both Kusama and Polkadot wasm runtimes for parachain builds.

### ISSUE THREAD

**Issue by chrisdcosta** [paritytech/srtool#56]
When Srtool compiles it stores the wasm runtime in the path `srtool>release>wbuild`. 

I am working with a parachain, and it seems to also compile not only the parachain wasm runtime, but also Polkadot and Kusama wasm runtimes stored in the same directory. 

In my opinion it is completely unnecessary to build the Kusama and Polkadot wasm runtimes separately as this would have a significant detrimental impact on performance of Srtool compile times.

Is there a reason for doing this?

**Comment by chevdor** [comment]
Hello @chrisdcosta,

I am surprised about that since we need to specifically pass the runtime we want to build.
If you previously built other runtimes, yes, they will be stored into the same directory but AFAIK they are not built unless requested.

Did you try right after cleaning your `target/srtool` folder ?

Could you share the logs of your run as well as the command you used ?

**Comment by chevdor** [comment]
@chrisdcosta I am closing this issue, please reopen if you still run into the issue and can provide answers to my questions.
